# Generated by Django 4.2.11 on 2024-03-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Код активації'),
        ),
    ]
