# Generated by Django 4.2.11 on 2024-03-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseadvertisement',
            options={'ordering': ('-created_timestamp',), 'verbose_name': 'Оголошення', 'verbose_name_plural': 'Оголошення'},
        ),
        migrations.AddField(
            model_name='baseadvertisement',
            name='css_style',
            field=models.TextField(default='background-color: rgb(213, 200, 12);', max_length=600, verbose_name='CSS Стилі'),
        ),
        migrations.AlterField(
            model_name='baseadvertisement',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Опис оголошення'),
        ),
        migrations.AlterField(
            model_name='baseadvertisement',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активне (тільки одне)'),
        ),
        migrations.AlterField(
            model_name='baseadvertisement',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Назва'),
        ),
    ]
