# Generated by Django 4.2.11 on 2024-04-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_baseadvertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseadvertisement',
            name='css_style',
            field=models.TextField(blank=True, default='', max_length=600, verbose_name='CSS Стилі'),
        ),
        migrations.AlterField(
            model_name='baseadvertisement',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активне'),
        ),
    ]
