# Generated by Django 4.2.11 on 2024-03-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_product_created_timestamp_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='SEO ключі'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ціна'),
        ),
    ]
