# Generated by Django 4.2.11 on 2024-03-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_categories_slug_alter_products_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table=None,
        ),
    ]
