# Generated by Django 4.2.11 on 2024-04-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_product_options_alter_product_meta_keywords'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'name', 'slug', 'description', 'meta_keywords'], name='products_id_b7fc0c_idx'),
        ),
    ]
