# Generated by Django 4.2.11 on 2024-03-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('sale_date',), 'verbose_name': 'Товар замовлення', 'verbose_name_plural': 'Товари замовлення'},
        ),
    ]
